### PR TITLE
Add Docker for development environment

### PR DESCRIPTION
**Pull request by nicolasleger**
See new `README` instructions to test Docker setup.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Thanks for your contribution, @nicolasleger !

When running `docker run -P -t openwhyd-react`, I'm getting:

```
Starting the development server...

(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Compiled successfully!
The app is running at:
  http://localhost:3000/
```

And getting `ERR_CONNECTION_REFUSED` from `http://localhost:3000`.

Are you getting the same behavior?

**Comment by nicolasleger** [comment]
@adrienjoly Sorry the good working command to launch is `docker run -p 3000:3000 -t openwhyd-react`. I fixed the `README`.

**Comment by nicolasleger** [comment]
The warning seems to come from the non browser presence in the container, see https://github.com/BrowserSync/browser-sync/issues/1229

**Comment by adrienjoly** [comment]
Now it's showing a "Welcome to React" page! Good job, Nicolas! 👍

**Comment by adrienjoly** [comment]
fixes #1.

**Pull request merged**
