### PR TITLE
Upgrades to latest versions react-scripts and react

### PR DESCRIPTION
**Pull request by mauricesvay**
This PR upgrades `react-scripts` and `react` to latest versions. The project is currently using an almost year-old version.

When this PR is merged, developers will need to rebuild the docker image as described in the README to get the changes.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Thanks, @mauricesvay!
Were you able to make the client work? (cf #1)

**Comment by mauricesvay** [comment]
@adrienjoly yes, it works without issues (with docker or without).

**Comment by mauricesvay** [comment]
Sorry, I think I've read too quickly. I haven't tested the `develop` branch, just `master`.

**Comment by adrienjoly** [comment]
@mauricesvay I don't even know what's supposed to work, and what's the difference between what's on `master` and `develop` branches...

=> Not sure if it's worth continuing from this old codebase, or start a fresh one.

EDIT: Maybe @SkinyMonkey can reply by providing status about this repo.

**Comment by adrienjoly** [comment]
@mauricesvay: @SkinyMonkey said that he's abandoned this repo and worked on a new one instead. See this discussion for more info: https://github.com/openwhyd/openwhyd-react/issues/1#issuecomment-341997100

=> I'm closing this PR. Sorry for not having updated the status of this project before you sent it... 😓

**Pull request closed without merging**
